// Auto generated by java fx
// Alternative entry point than the main class
// This entry point is more safe as the Launcher class has no direct dependency on JavaFX classes,
// so the classloader doesn't attempt to resolve JavaFX types at startup. It gives the module system
// time to initialize properly before JavaFX is touched... or at least that's what AI told me
// Whether you run main or launcher doesn't matter within an IDE or using maven with the JavaFX plugin
// It might matter when we compile an executable jar

package com.cps406;

import javafx.application.Application;

public class Launcher {
    public static void main(String[] args) {
        Application.launch(Main.class, args);
    }
}
