// Auto generated by javafx template
// Entry point of our program

package com.cps406;

import com.cps406.controllers.EnterController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.*;
import javafx.stage.Stage;
import javafx.scene.image.Image;

import java.io.IOException;

public class Main extends Application {
    /**
     * entry point
     * this will call launch, which will call start method which we overrode below
     * @param args arg matey
     */
    public static void main (String[] args)
    { launch(args); }

    /**
     * load the first scene and other initial startup stuff
     * @param stage the stage of our application
     * @throws IOException if loading scene fails
     */
    @Override
    public void start(Stage stage) throws IOException {
        // Create new app state
        // This will act as a wrapper that contains the sprint manager and the product backlog
        AppState appState = new AppState();

        // initialize database
        DatabaseConnection.initialize();

        // Load entry scene
        FXMLLoader loader = new FXMLLoader(getClass().getResource("Enter.fxml"));
        Parent root = loader.load();

        // Create a new scene and set its style sheet
        Scene scene = new Scene(root);
        scene.getStylesheets().add(getClass().getResource("styles.css").toExternalForm());

        EnterController ec = loader.getController();
        ec.setAppState(appState);

        // Set the scene
        stage.setScene(scene);

        // Set the icon and title
        stage.setTitle("Product Backlog Manager");
        stage.getIcons().add(
                new Image(getClass().getResourceAsStream("/com/cps406/logo.png")));

        // Show the stage
        stage.show();
    }
}
